USE FinalProject;
CREATE  TABLE DEALER(
DealerID Char(5) NOT NULL,
FName Char(15) NOT NULL,
LName Char(15) NOT NULL,
BusinessName Char(30) NOT NULL,
Address Char(50) NOT NULL,
City Char(20) NOT NULL,
State Char(2) NOT NULL,
Zip Int NOT NULL,
Phone BigInt NOT NULL,
TaxID BigInt NOT NULL,
Comments Char(150) NOT NULL,
CONSTRAINT DEALER_PK PRIMARY KEY(DealerID)
);

CREATE TABLE BOOTH(
BoothID Char(5) NOT NULL, 
Location Char(20) NOT NULL, 
Availability Char(50) NOT NULL, 
Color Char(30) NOT NULL, 
Rafter Bit NOT NULL default (0),
Carpeting Bit NOT NULL default (0),
CONSTRAINT BOOTH_PK PRIMARY KEY(BoothID)
);

CREATE TABLE LEASES(
LeaseID Char(5) NOT NULL, 
RentAmount Int NOT NULL, 
Commission Float NOT NULL, 
BoothID Char(5) NOT NULL,
DealerID Char(5) NOT NULL,
CONSTRAINT LEASES_PK PRIMARY KEY(LeaseID), 
CONSTRAINT LEASES_BOOTH_FK FOREIGN KEY(BoothID) REFERENCES BOOTH(BoothID),
CONSTRAINT LEASES_DEALER_FK FOREIGN KEY(DealerID) REFERENCES DEALER(DealerID)
);

CREATE TABLE PRODUCT(
ProductID char(5) NOT NULL, 
ProductName Char(30) NOT NULL, 
ProductType Char(30) NOT NULL, 
Price Int NOT NULL, 
CONSTRAINT PRODUCT_PK PRIMARY KEY(ProductID)
);

CREATE TABLE SALES(
TransactionID Char(10) NOT NULL, 
DateSold Date NOT NULL, 
DealerID Char(5) NOT NULL, 
ProductID Char(5) NOT NULL, 
CONSTRAINT SALES_PK PRIMARY KEY(TransactionID),
CONSTRAINT SALES_DEALER FOREIGN KEY(DealerID) REFERENCES DEALER(DealerID),
CONSTRAINT SALES_PRODUCT FOREIGN KEY(ProductID) REFERENCES PRODUCT(ProductID)
);
